package Soal5;

import database.dbconnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author aizarrahima
 */
public class AddProduct extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;
    ResultSet rs;

    dbconnection koneksi;
    
    int stock, harga, kode_produk;
    String nama_produk, detail_produk;
    
    public AddProduct() {
        initComponents();
        
        koneksi = new dbconnection();
        conn = koneksi.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAddProduct = new javax.swing.JPanel();
        jLabelNama = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jLabelHarga = new javax.swing.JLabel();
        jTextFieldHarga = new javax.swing.JTextField();
        jLabelStock = new javax.swing.JLabel();
        jTextFieldStock = new javax.swing.JTextField();
        jLabelDetailProduk = new javax.swing.JLabel();
        jScrollPaneDetailProduk = new javax.swing.JScrollPane();
        jTextAreaDetailProduk = new javax.swing.JTextArea();
        jButtonAdd = new javax.swing.JButton();
        jLabelKodeProduk = new javax.swing.JLabel();
        jTextFieldKodeProduk = new javax.swing.JTextField();
        jPanelPesan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPesan = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelAddProduct.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N

        jLabelNama.setText("Nama");

        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });

        jLabelHarga.setText("Harga");

        jTextFieldHarga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldHargaFocusLost(evt);
            }
        });
        jTextFieldHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaActionPerformed(evt);
            }
        });

        jLabelStock.setText("Stock");

        jTextFieldStock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldStockFocusLost(evt);
            }
        });
        jTextFieldStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStockActionPerformed(evt);
            }
        });

        jLabelDetailProduk.setText("Detail Produk");

        jTextAreaDetailProduk.setColumns(20);
        jTextAreaDetailProduk.setRows(5);
        jScrollPaneDetailProduk.setViewportView(jTextAreaDetailProduk);

        jButtonAdd.setText("Tambah");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelKodeProduk.setText("Kode ");

        jTextFieldKodeProduk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldKodeProdukFocusLost(evt);
            }
        });
        jTextFieldKodeProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKodeProdukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddProductLayout = new javax.swing.GroupLayout(jPanelAddProduct);
        jPanelAddProduct.setLayout(jPanelAddProductLayout);
        jPanelAddProductLayout.setHorizontalGroup(
            jPanelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddProductLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAdd)
                    .addGroup(jPanelAddProductLayout.createSequentialGroup()
                        .addGroup(jPanelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNama)
                            .addComponent(jLabelHarga)
                            .addComponent(jLabelStock)
                            .addComponent(jLabelKodeProduk)
                            .addComponent(jLabelDetailProduk))
                        .addGap(21, 21, 21)
                        .addGroup(jPanelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldKodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneDetailProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelAddProductLayout.setVerticalGroup(
            jPanelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNama)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKodeProduk)
                    .addComponent(jTextFieldKodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHarga)
                    .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStock)
                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddProductLayout.createSequentialGroup()
                        .addComponent(jLabelDetailProduk)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelAddProductLayout.createSequentialGroup()
                        .addComponent(jScrollPaneDetailProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdd)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );

        jPanelPesan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N

        jTextAreaPesan.setColumns(20);
        jTextAreaPesan.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPesan);

        javax.swing.GroupLayout jPanelPesanLayout = new javax.swing.GroupLayout(jPanelPesan);
        jPanelPesan.setLayout(jPanelPesanLayout);
        jPanelPesanLayout.setHorizontalGroup(
            jPanelPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelPesanLayout.setVerticalGroup(
            jPanelPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesanLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jTextFieldHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        harga = Integer.parseInt(jTextFieldHarga.getText());
        stock = Integer.parseInt(jTextFieldStock.getText());
        kode_produk = Integer.parseInt(jTextFieldKodeProduk.getText());
        nama_produk = jTextFieldNama.getText();
        detail_produk = jTextAreaDetailProduk.getText();
        
        insertData();
        clearForm();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStockActionPerformed

    private void jTextFieldKodeProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKodeProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKodeProdukActionPerformed

    private void jTextFieldKodeProdukFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldKodeProdukFocusLost
        // TODO add your handling code here:
        checkKode();
    }//GEN-LAST:event_jTextFieldKodeProdukFocusLost

    private void jTextFieldHargaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldHargaFocusLost
        // TODO add your handling code here:
        checkHarga();
    }//GEN-LAST:event_jTextFieldHargaFocusLost

    private void jTextFieldStockFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldStockFocusLost
        // TODO add your handling code here:
        checkStock();
    }//GEN-LAST:event_jTextFieldStockFocusLost

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macos".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }
    
    private void checkKode() {
        String errorKode = "Silakan input kode berupa angka";

        String kodeProdukStr = jTextFieldKodeProduk.getText();

        try {
            kode_produk = Integer.parseInt(kodeProdukStr);

            jTextAreaPesan.setText("");
        } catch (NumberFormatException e) {
            if (!kodeProdukStr.matches("\\d+")) {
                jTextAreaPesan.setText(errorKode);
            }
        }
    }
    
    private void checkStock() {
        String errorStock = "Silakan input stok berupa angka";
        
        String stockStr = jTextFieldStock.getText();

        try {
            stock = Integer.parseInt(stockStr);
            
            jTextAreaPesan.setText("");
        } catch (NumberFormatException e) {
            if (!stockStr.matches("\\d+")) {
                jTextAreaPesan.setText(errorStock);
            }
        }
    }
    
    private void checkHarga() {
        String errorHarga = "Silakan input harga berupa angka";
        
        String hargaStr = jTextFieldHarga.getText();

        try {
            harga = Integer.parseInt(hargaStr);
            
            jTextAreaPesan.setText("");
        } catch (NumberFormatException e) {
            if (!hargaStr.matches("\\d+")) {
                jTextAreaPesan.setText(errorHarga);
            }
        }
    }

    
    private boolean insertData() {
        try {
            stmt = conn.createStatement();

            // query
            int insert = stmt.executeUpdate("INSERT INTO produk(kode_produk, nama_produk, harga, stok, detail_produk) "
                    + "VALUES (" + kode_produk + ", '" + nama_produk + "', " + harga + " , " + stock + ", '" + detail_produk+"')");

            if (insert == 1) {
                JOptionPane.showMessageDialog(rootPane, "Data Berhasil Tersimpan");
                
                dispose();
                
                ListProduct listProduct = new ListProduct();
                listProduct.setVisible(true);
            }
            return true;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error 2: " + ex.getMessage());
        }
        return false;
    }
    
    private void clearForm() {
        jTextFieldNama.setText("");
        jTextAreaDetailProduk.setText("");
        jTextFieldHarga.setText("");
        jTextFieldStock.setText("");
        jTextFieldKodeProduk.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabelDetailProduk;
    private javax.swing.JLabel jLabelHarga;
    private javax.swing.JLabel jLabelKodeProduk;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JPanel jPanelAddProduct;
    private javax.swing.JPanel jPanelPesan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneDetailProduk;
    private javax.swing.JTextArea jTextAreaDetailProduk;
    private javax.swing.JTextArea jTextAreaPesan;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldKodeProduk;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldStock;
    // End of variables declaration//GEN-END:variables
}
