package Soal5;

import database.dbconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aizarrahima
 */
public class AddTransactions extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;
    ResultSet rs;

    dbconnection koneksi;

    String Tanggal;
    private DefaultTableModel model;

    public void totalBiaya() {
        int jumlahBaris = jTable1.getRowCount();
        int totalBiaya = 0;
        int jumlahBarang, hargaBarang;
        for (int i = 0; i < jumlahBaris; i++) {
            jumlahBarang = Integer.parseInt(jTable1.getValueAt(i, 2).toString());
            hargaBarang = Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            totalBiaya = totalBiaya + (jumlahBarang * hargaBarang);
        }
        jTextFieldTotalBayar.setText(String.valueOf(totalBiaya));
        jTextFieldTampil.setText("Rp " + totalBiaya + ",00");
    }

    public void getData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{
            jTextFieldIdProduk.getText(),
            jTextFieldNamaProduk.getText(),
            jTextFieldJumlah.getText(),
            jTextFieldHarga.getText(),
            jTextFieldTotalBayar.getText()
        });
    }

    public void kosong() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }

    public void utama() {
        jTextFieldIdProduk.setText("");
        jTextFieldNamaProduk.setText("");
        jTextFieldJumlah.setText("");
        jTextFieldHarga.setText("");
    }

    public void clear() {
        jTextFieldNamaCustomer.setText("");
        jTextFieldTotalBayar.setText("");
        jTextFieldBayar.setText("");
        jTextFieldKembalian.setText("");
        jTextFieldTampil.setText("");
    }

    public void clear2() {
        jTextFieldIdProduk.setText("");
        jTextFieldNamaProduk.setText("");
        jTextFieldHarga.setText("");
        jTextFieldJumlah.setText("");
    }

    public void addTransaction() {
        int jumlah, harga, total;

        jumlah = Integer.valueOf(jTextFieldJumlah.getText());
        harga = Integer.valueOf(jTextFieldHarga.getText());
        total = jumlah * harga;

        jTextFieldTotalBayar.setText(String.valueOf(total));

        getData();
        totalBiaya();
        clear2();
        jTextFieldIdProduk.requestFocus();
    }

    public AddTransactions() {
        initComponents();

        koneksi = new dbconnection();
        conn = koneksi.getConnection();

        //Create Table
        model = new DefaultTableModel();

        jTable1.setModel(model);

        model.addColumn("Id Produk");
        model.addColumn("Nama Produk");
        model.addColumn("Jumlah");
        model.addColumn("Harga");
        model.addColumn("Total");

        utama();
        Date date = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");

        jTextFieldTanggal.setText(s.format(date));
        jTextFieldTotalBayar.setText("0");
        jTextFieldBayar.setText("0");
        jTextFieldKembalian.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTransactionTitle = new javax.swing.JPanel();
        jLabelTransactionTitle = new javax.swing.JLabel();
        jTextFieldTampil = new javax.swing.JTextField();
        jLabelTanggal = new javax.swing.JLabel();
        jTextFieldTanggal = new javax.swing.JTextField();
        jLabelNamaCustomer = new javax.swing.JLabel();
        jTextFieldNamaCustomer = new javax.swing.JTextField();
        jLabelIdProduk = new javax.swing.JLabel();
        jTextFieldIdProduk = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jTextFieldNamaProduk = new javax.swing.JTextField();
        jLabelNamaProduk = new javax.swing.JLabel();
        jTextFieldHarga = new javax.swing.JTextField();
        jLabelHarga = new javax.swing.JLabel();
        jTextFieldJumlah = new javax.swing.JTextField();
        jLabelJumlah = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonTambah = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jTextFieldTotalBayar = new javax.swing.JTextField();
        jLabelTotalHarga = new javax.swing.JLabel();
        jLabelBayar = new javax.swing.JLabel();
        jTextFieldBayar = new javax.swing.JTextField();
        jTextFieldKembalian = new javax.swing.JTextField();
        jLabelKembalian = new javax.swing.JLabel();
        jButtonSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTransactionTitle.setBackground(new java.awt.Color(255, 204, 204));

        jLabelTransactionTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTransactionTitle.setText("Transactions");

        javax.swing.GroupLayout jPanelTransactionTitleLayout = new javax.swing.GroupLayout(jPanelTransactionTitle);
        jPanelTransactionTitle.setLayout(jPanelTransactionTitleLayout);
        jPanelTransactionTitleLayout.setHorizontalGroup(
            jPanelTransactionTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransactionTitleLayout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabelTransactionTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTransactionTitleLayout.setVerticalGroup(
            jPanelTransactionTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransactionTitleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelTransactionTitle)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTextFieldTampil.setBackground(new java.awt.Color(255, 153, 153));
        jTextFieldTampil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextFieldTampil.setText("Rp. 0");
        jTextFieldTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTampilActionPerformed(evt);
            }
        });

        jLabelTanggal.setText("Tanggal");

        jTextFieldTanggal.setEnabled(false);

        jLabelNamaCustomer.setText("Nama Customer");

        jLabelIdProduk.setText("ID Produk");

        jTextFieldIdProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdProdukActionPerformed(evt);
            }
        });

        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });

        jTextFieldNamaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaProdukActionPerformed(evt);
            }
        });

        jLabelNamaProduk.setText("Nama Produk");

        jTextFieldHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaActionPerformed(evt);
            }
        });

        jLabelHarga.setText("Harga");

        jTextFieldJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJumlahActionPerformed(evt);
            }
        });

        jLabelJumlah.setText("Jumlah");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jTextFieldTotalBayar.setBackground(new java.awt.Color(242, 242, 242));
        jTextFieldTotalBayar.setEnabled(false);

        jLabelTotalHarga.setText("Total Bayar");

        jLabelBayar.setText("Bayar");

        jTextFieldBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBayarActionPerformed(evt);
            }
        });

        jTextFieldKembalian.setEnabled(false);

        jLabelKembalian.setText("Kembalian");

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTransactionTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextFieldIdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCari))
                                .addComponent(jLabelIdProduk))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNamaProduk))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelHarga))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelJumlah)
                                .addComponent(jTextFieldJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelTanggal)
                                .addComponent(jLabelNamaCustomer))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jTextFieldNamaCustomer))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldTampil, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelTotalHarga)
                                .addComponent(jLabelBayar)
                                .addComponent(jLabelKembalian))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldBayar)
                                .addComponent(jTextFieldKembalian)
                                .addComponent(jTextFieldTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTambah)
                    .addComponent(jButtonHapus)
                    .addComponent(jButtonSimpan))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTransactionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTanggal)
                    .addComponent(jTextFieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamaCustomer)
                    .addComponent(jTextFieldNamaCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdProduk)
                    .addComponent(jLabelNamaProduk)
                    .addComponent(jLabelHarga)
                    .addComponent(jLabelJumlah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCari)
                    .addComponent(jTextFieldNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTambah)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHapus)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSimpan))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldTampil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalHarga)
                    .addComponent(jTextFieldTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBayar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelKembalian))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIdProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdProdukActionPerformed

    private void jTextFieldNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaProdukActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        // TODO add your handling code here:
        addTransaction();
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jTextFieldJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJumlahActionPerformed
        // TODO add your handling code here:
        addTransaction();
    }//GEN-LAST:event_jTextFieldJumlahActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        model.removeRow(row);
        totalBiaya();
        jTextFieldBayar.setText("0");
        jTextFieldKembalian.setText("0");
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jTextFieldBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBayarActionPerformed
        // TODO add your handling code here:
        int total, bayar, kembalian;

        total = Integer.valueOf(jTextFieldTotalBayar.getText());
        bayar = Integer.valueOf(jTextFieldBayar.getText());

        if (total > bayar) {
            JOptionPane.showMessageDialog(null, "Uang tidak cukup untuk melakukan pembayaran");
        } else {
            kembalian = bayar - total;
            jTextFieldKembalian.setText(String.valueOf(kembalian));
        }
    }//GEN-LAST:event_jTextFieldBayarActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        saveData();
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        PopupBarang popupBarang = new PopupBarang();
        popupBarang.setVisible(true);
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jTextFieldTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTampilActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldTampilActionPerformed

    private void jTextFieldHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macos".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTransactions().setVisible(true);
            }
        });
    }

    private void saveData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int total = Integer.parseInt(jTextFieldTotalBayar.getText());
        String nama_customer = jTextFieldNamaCustomer.getText();

        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            // Establish the connection
            conn = new dbconnection().getConnection();

            // Insert the customer and retrieve the generated id
            String insertCustomerSQL = "INSERT INTO pelanggan(nama) VALUES (?)";
            PreparedStatement pstmt = conn.prepareStatement(insertCustomerSQL, Statement.RETURN_GENERATED_KEYS);
            pstmt.setString(1, nama_customer);
            pstmt.executeUpdate();

            // Retrieve the generated customer id
            rs = pstmt.getGeneratedKeys();
            int id_pelanggan = -1;
            if (rs.next()) {
                id_pelanggan = rs.getInt(1);
            }

            // Check if we got a valid customer id
            if (id_pelanggan == -1) {
                throw new SQLException("Failed to retrieve customer ID.");
            }

            // Date Formated
            String tanggalStr = jTextFieldTanggal.getText();
            java.sql.Date sqlDate = null;

            if (tanggalStr != null && !tanggalStr.isEmpty()) {
                try {
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    java.util.Date parsedDate = dateFormat.parse(tanggalStr);
                    sqlDate = new java.sql.Date(parsedDate.getTime());
                } catch (ParseException e) {
                    // Handle parsing error
                    e.printStackTrace();
                }
            } else {
                // Handle null or empty date string
                System.out.println("Date string is null or empty.");
            }

            // Insert the transaction
            String insertTransactionSQL = "INSERT INTO transaksi(id_pelanggan, tanggal, total_bayar) VALUES (?, ?, ?)";
            pstmt = conn.prepareStatement(insertTransactionSQL, Statement.RETURN_GENERATED_KEYS);
            pstmt.setInt(1, id_pelanggan);
            pstmt.setDate(2, sqlDate);
            pstmt.setInt(3, total);
            pstmt.executeUpdate();

            // Retrive the generated transaction id
            rs = pstmt.getGeneratedKeys();
            int id_transaksi = -1;
            if (rs.next()) {
                id_transaksi = rs.getInt(1);
            }

            // Check if we got a valid transaction id
            if (id_transaksi == -1) {
                throw new SQLException("Failed to retrieve transaction ID.");
            }

            // Insert the transaction
            int baris = jTable1.getRowCount();

            for (int i = 0; i < baris; i++) {
                String insertTransactionDetailSQL = "INSERT INTO detail_transaksi(id_transaksi, id_produk, jumlah, harga, total_harga) VALUES (?, ?, ?, ?, ?)";
                pstmt = conn.prepareStatement(insertTransactionDetailSQL);
                pstmt.setInt(1, id_transaksi);
                pstmt.setInt(2, Integer.parseInt((String) jTable1.getValueAt(i, 0)));
                pstmt.setInt(3, Integer.parseInt((String) jTable1.getValueAt(i, 2)));
                pstmt.setInt(4, Integer.parseInt((String) jTable1.getValueAt(i, 3)));
                pstmt.setInt(5, Integer.parseInt((String) jTable1.getValueAt(i, 4)));
                pstmt.executeUpdate();
            };

            JOptionPane.showMessageDialog(null, "Data berhasil disimpan.");

            dispose();
            ListTransaction listTransaction = new ListTransaction();
            listTransaction.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            System.out.println("Gagal Menyimpan Data: " + ex.getMessage());
        } finally {
            // Close resources
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                System.out.println("Failed to close resources: " + ex.getMessage());
            }
        }
        clear();
        utama();
        kosong();
        jTextFieldTampil.setText("Rp. 0");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JLabel jLabelBayar;
    private javax.swing.JLabel jLabelHarga;
    private javax.swing.JLabel jLabelIdProduk;
    private javax.swing.JLabel jLabelJumlah;
    private javax.swing.JLabel jLabelKembalian;
    private javax.swing.JLabel jLabelNamaCustomer;
    private javax.swing.JLabel jLabelNamaProduk;
    private javax.swing.JLabel jLabelTanggal;
    private javax.swing.JLabel jLabelTotalHarga;
    private javax.swing.JLabel jLabelTransactionTitle;
    private javax.swing.JPanel jPanelTransactionTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBayar;
    public static javax.swing.JTextField jTextFieldHarga;
    public static javax.swing.JTextField jTextFieldIdProduk;
    private javax.swing.JTextField jTextFieldJumlah;
    private javax.swing.JTextField jTextFieldKembalian;
    private javax.swing.JTextField jTextFieldNamaCustomer;
    public static javax.swing.JTextField jTextFieldNamaProduk;
    private javax.swing.JTextField jTextFieldTampil;
    private javax.swing.JTextField jTextFieldTanggal;
    private javax.swing.JTextField jTextFieldTotalBayar;
    // End of variables declaration//GEN-END:variables
}
