package Soal5;

/**
 *
 * @author aizarrahima
 */
public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDashboard = new javax.swing.JMenu();
        jMenuItemHome = new javax.swing.JMenuItem();
        jMenuProducts = new javax.swing.JMenu();
        jMenuItemAddProduct = new javax.swing.JMenuItem();
        jMenuItemUpdateProduct = new javax.swing.JMenuItem();
        jMenuItemDeleteProduct = new javax.swing.JMenuItem();
        jMenuListProduct = new javax.swing.JMenuItem();
        jMenuTransactions = new javax.swing.JMenu();
        jMenuItemAddTransaction = new javax.swing.JMenuItem();
        jMenuItemListTransaction = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuDashboard.setText("Dashboard");

        jMenuItemHome.setText("Home");
        jMenuItemHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHomeActionPerformed(evt);
            }
        });
        jMenuDashboard.add(jMenuItemHome);

        jMenuBar1.add(jMenuDashboard);

        jMenuProducts.setText("Products");

        jMenuItemAddProduct.setText("Add Product");
        jMenuItemAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddProductActionPerformed(evt);
            }
        });
        jMenuProducts.add(jMenuItemAddProduct);

        jMenuItemUpdateProduct.setText("Update Product");
        jMenuItemUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdateProductActionPerformed(evt);
            }
        });
        jMenuProducts.add(jMenuItemUpdateProduct);

        jMenuItemDeleteProduct.setText("Delete Product");
        jMenuItemDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteProductActionPerformed(evt);
            }
        });
        jMenuProducts.add(jMenuItemDeleteProduct);

        jMenuListProduct.setText("List Product");
        jMenuListProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListProductActionPerformed(evt);
            }
        });
        jMenuProducts.add(jMenuListProduct);

        jMenuBar1.add(jMenuProducts);

        jMenuTransactions.setText("Transactions");

        jMenuItemAddTransaction.setText("Add Transactions");
        jMenuItemAddTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddTransactionActionPerformed(evt);
            }
        });
        jMenuTransactions.add(jMenuItemAddTransaction);

        jMenuItemListTransaction.setText("List Transaction");
        jMenuItemListTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListTransactionActionPerformed(evt);
            }
        });
        jMenuTransactions.add(jMenuItemListTransaction);

        jMenuBar1.add(jMenuTransactions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddProductActionPerformed
        // TODO add your handling code here:
        dispose();

        AddProduct formAddProduct = new AddProduct();
        formAddProduct.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddProductActionPerformed

    private void jMenuItemUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdateProductActionPerformed
        // TODO add your handling code here:
        dispose();

        UpdateProduct formUpdateDeleteProduct = new UpdateProduct();
        formUpdateDeleteProduct.setVisible(true);
    }//GEN-LAST:event_jMenuItemUpdateProductActionPerformed

    private void jMenuItemHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHomeActionPerformed
        // TODO add your handling code here:
        dispose();

        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jMenuItemHomeActionPerformed

    private void jMenuItemDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteProductActionPerformed
        // TODO add your handling code here:
        dispose();

        UpdateProduct formUpdateProduct = new UpdateProduct();
        formUpdateProduct.setVisible(true);
    }//GEN-LAST:event_jMenuItemDeleteProductActionPerformed

    private void jMenuListProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListProductActionPerformed
        // TODO add your handling code here:
        dispose();

        ListProduct listProduct = new ListProduct();
        listProduct.setVisible(true);
    }//GEN-LAST:event_jMenuListProductActionPerformed

    private void jMenuItemListTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListTransactionActionPerformed
        // TODO add your handling code here:
        dispose();

        ListTransaction listTransaction = new ListTransaction();
        listTransaction.setVisible(true);
    }//GEN-LAST:event_jMenuItemListTransactionActionPerformed

    private void jMenuItemAddTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddTransactionActionPerformed
        // TODO add your handling code here:
        dispose();

        AddTransactions addTransactions = new AddTransactions();
        addTransactions.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddTransactionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macos".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDashboard;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAddProduct;
    private javax.swing.JMenuItem jMenuItemAddTransaction;
    private javax.swing.JMenuItem jMenuItemDeleteProduct;
    private javax.swing.JMenuItem jMenuItemHome;
    private javax.swing.JMenuItem jMenuItemListTransaction;
    private javax.swing.JMenuItem jMenuItemUpdateProduct;
    private javax.swing.JMenuItem jMenuListProduct;
    private javax.swing.JMenu jMenuProducts;
    private javax.swing.JMenu jMenuTransactions;
    // End of variables declaration//GEN-END:variables
}
